version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/Terraform"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      terraform-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      actions-deps:
        patterns:
          - "*"