name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: Terraform
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_API_TOKEN }}
      LINODE_TOKEN: ${{ secrets.LINODE_API_TOKEN }}
      ROOT_PASSWORD: ${{ secrets.LINODE_ROOT_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Plan
        run: terraform plan -var="linode_token=$LINODE_TOKEN" -var="root_password=$ROOT_PASSWORD"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="linode_token=$LINODE_TOKEN" -var="root_password=$ROOT_PASSWORD"
