name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action (apply or destroy)'
        required: true
        default: 'apply'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      LINODE_TOKEN: ${{ secrets.LINODE_API_TOKEN }}
      ROOT_PASSWORD: ${{ secrets.LINODE_ROOT_PASSWORD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: Terraform
        run: terraform init

      - name: Terraform ${{ github.event.inputs.action }}
        working-directory: Terraform
        run: terraform ${{ github.event.inputs.action }} -auto-approve
          -var="linode_token=$LINODE_TOKEN"
          -var="root_password=$ROOT_PASSWORD"
